### ISSUE TITLE
Vnc Support (?)

### ISSUE THREAD

**Issue by akrista** [Antiz96/Ankama-Launcher-Container#27]
Hey, your repo looks really interesting. I'm currently reviewing it to give it a try. Sorry for the intrusion, but I wanted to ask if you have considered adding VNC support to it, either with jlesage or kasmvnc. It would be great to be able to run Ankama Launcher headless and play the game from a browser.

Amazing work btw!

**Comment by Antiz96** [comment]
Hi @Akrista,

Thanks a lot for your support and interest! I appreciate it :slightly_smiling_face: 

Thanks also for the suggestion. However, I'm not considering adding VNC support for now to be honest.
While the idea is interesting, I'd like to keep this Ankama Launcher container as simple as it currently is.

The initial goal was to provide a simple "all in one" and distro agnostic solution to run the Ankama Launcher and the associated games, basically what the official Ankama Launcher AppImage should have been in the first place in my opinion (which it's currently not unfortunately). And I'd like to stick to that, at least for now.

I'm closing this issue for now, but I'll re-open it if I ever change my mind and consider adding VNC support.

Thanks once again for the kind words!
